apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-cpr
  annotations:
    kubernetes.io/ingress.class: nginx  
spec:  
  rules:
  - http:
      paths:
      - path: /app1/
        backend:
          service:
            name: app1-nginx-clusterip-service
            port: 80
      - path: /app2/
        backend:
          service:
            name: app2-nginx-clusterip-service
            port: 80          
      - path: /
        backend:
          service:
            name: usermgmt-webapp-clusterip-service
            port: 80